# Generated by Django 5.2.1 on 2025-06-30 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='combo',
            name='imagen',
            field=models.ImageField(default='default.png', upload_to='combos/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='platoespecial',
            name='imagen',
            field=models.ImageField(default='default.png', upload_to='platos_especiales/'),
            preserve_default=False,
        ),
    ]
