# Generated by Django 5.2.1 on 2025-06-30 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_combo_imagen_platoespecial_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combo',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/'),
        ),
        migrations.AlterField(
            model_name='platoespecial',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='platos_especiales/'),
        ),
    ]
