# Generated by Django 5.2.1 on 2025-06-30 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_combo_imagen_alter_platoespecial_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combo',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='combos/'),
        ),
    ]
