# Generated by Django 5.2.1 on 2025-06-30 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_combo_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comboplato',
            name='combo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platos_combo', to='myapp.combo'),
        ),
    ]
