# Generated by Django 5.2.1 on 2025-06-30 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_comboplato_combo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comboplato',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='comboplato',
            name='plato',
        ),
        migrations.AddField(
            model_name='comboplato',
            name='maximo_opciones',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='comboplato',
            name='platos',
            field=models.ManyToManyField(to='myapp.platoespecial'),
        ),
        migrations.AddField(
            model_name='comboplato',
            name='titulo_opcion',
            field=models.CharField(default='Sin titulo', help_text='Ej: Escoge tu bebida', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comboplato',
            name='combo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comboplatos', to='myapp.combo'),
        ),
        migrations.AlterField(
            model_name='platoespecial',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='platos/'),
        ),
    ]
