# Generated by Django 5.2.1 on 2025-07-01 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_comboplato_cantidad_remove_comboplato_plato_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comboplato',
            name='titulo_opcion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
