# Generated by Django 5.2.1 on 2025-07-02 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_comboplato_titulo_opcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidocombo',
            name='platos',
            field=models.ManyToManyField(blank=True, to='myapp.platoespecial'),
        ),
    ]
